### ISSUE TITLE
Limit content output on index.php

### ISSUE THREAD

**Issue by kohfuchs** [DannyCooper/arke#1]
Hi,
I really like your work that you've done here! Thank you for creating this template. :+1:

I just wonder, if there is a possibility to limit the "the_content()" output on the homepage if you are using the "Display last post" option from WP ? 
It would be good to just display the title on the front page an load the full content page with comments with a klick on the link. (As it already works)

Thanks for your comments!

**Comment by DannyCooper** [comment]
Hi @1fuchsr,

You should be able to achieve that by replacing 

`the_content( esc_html__( 'Continue reading &rarr;', 'arke' ) );` 

in content.php with:

```
if( ! is_front_page() ) {
    the_content( esc_html__( 'Continue reading &rarr;', 'arke' ) );
}
```

**Comment by kohfuchs** [comment]
Workes like a charm. 
Thank you much!
