### ISSUE TITLE
"Visit all posts" invisible

### ISSUE THREAD

**Issue by asifimtious** [DannyCooper/arke#5]
Though the following code is inside the index.php —

```
<?php if ( get_page_by_path( 'archives' ) ) : ?>
	<footer class="site-footer">
		<a href="<?php echo esc_url( site_url( 'archives' ) ); ?>"><?php esc_html_e( 'View All Posts &rarr;', 'arke' ); ?></a>
	</footer><!-- .site-footer -->
<?php else : ?>
	<?php arke_the_posts_navigation(); ?>
<?php endif; ?>
	?php wp_footer(); ?>
```

But the "View all posts" option is not appearing from all the pages along with the bottom of the homepage's single article.

**Comment by DannyCooper** [comment]
Hi @asifprome,

The code checks if a page exists with the 'archives' permalink before outputting the link. Have you created that page?

Ref: https://docs.olympusthemes.com/kb/arke-theme/setup-guide/

**Comment by asifimtious** [comment]
The homepage has a "visit all posts" button in the footer. Screenshot: https://prnt.sc/vyz822
Even I put "blog pages show at most" to "01", the "visit all posts" button doesn't appear. Screenshot: https://prnt.sc/vyz98c

**Comment by DannyCooper** [comment]
Hi @asifprome,

Have you created the archive page as detailed in the docs?

**Comment by asifimtious** [comment]
Yes, I did. Here is the screenshot: https://prnt.sc/vyzjic

**Comment by DannyCooper** [comment]
That does look right, can you send a link to the site so I can take a look?

**Comment by asifimtious** [comment]
It's actually on my local server. Is that option working on your side?

**Comment by DannyCooper** [comment]
Yes, you can see it here - https://demo.olympusthemes.com/arke/

The site is using the latest versions of WordPress + Arke.

**Comment by asifimtious** [comment]
Yeah, I checked that.

I did the following settings—

1. settings>reading (blog show max 1)
2. archive template to the archive page

Did I miss something else?

**Comment by DannyCooper** [comment]
No, that is exactly right. I can't understand why it isn't working on your local setup.
